module.exports = [
  {
    code: "A",
    name: "Organic Beetroot Powder",
    shortName: "Beetroot",
    slug: "beetroot",
    description:
      "Naturally rich in nitrates and antioxidants, beetroot supports stamina, heart health, and circulation.",
    keyBenefits: ["Stamina", "Heart health", "Circulation"],
    price: 299,
    mrp: 399,
    size: "200g",
    rating: 4.7,
    reviewsCount: 128,
    bestseller: true,
  },
  {
    code: "B",
    name: "Pure Gooseberry (Amla) Powder",
    shortName: "Amla",
    slug: "gooseberry",
    description:
      "Packed with natural Vitamin C, amla supports glowing skin, immunity, and digestive health.",
    keyBenefits: ["Glowing skin", "Immunity", "Digestive health"],
    price: 349,
    mrp: 449,
    size: "200g",
    rating: 4.8,
    reviewsCount: 94,
    bestseller: true,
  },
  {
    code: "C",
    name: "Moringa Superleaf Powder",
    shortName: "Moringa",
    slug: "moringa",
    description:
      "Nutrient-dense superleaf providing daily vitality, plant protein, and essential minerals.",
    keyBenefits: ["Daily vitality", "Plant protein", "Essential minerals"],
    price: 399,
    mrp: 499,
    size: "200g",
    rating: 4.7,
    reviewsCount: 143,
    bestseller: true,
  },
  {
    code: "D",
    name: "Everfit Daily Vitality Capsules",
    shortName: "Everfit",
    slug: "everfit",
    description:
      "Potent daily vitality capsules crafted for active professionals and holistic well-being.",
    keyBenefits: ["Daily vitality", "Holistic well-being"],
    price: 499,
    mrp: 649,
    size: "60 capsules",
    rating: 4.6,
    reviewsCount: 72,
    bestseller: true,
  },
  {
    code: "E",
    name: "Giloy Immunity Extract Powder",
    shortName: "Giloy",
    slug: "giloy-powder",
    description:
      "Ayurvedic rejuvenating herb traditionally renowned for boosting white blood cell immunity.",
    keyBenefits: ["Immunity", "White blood cell support"],
    price: 429,
    mrp: 549,
    size: "200g",
    rating: 4.8,
    reviewsCount: 101,
    bestseller: true,
  },
  {
    code: "F",
    name: "Neem Detox Powder",
    shortName: "Neem",
    slug: "neem",
    description:
      "Traditional Ayurvedic cleanser supporting clear skin, balanced gut, and internal purification.",
    keyBenefits: ["Clear skin", "Balanced gut", "Internal purification"],
    price: 389,
    mrp: 499,
    size: "200g",
    rating: 4.6,
    reviewsCount: 68,
    bestseller: false,
  },
];
